apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project
resources:
  - todo-app/manifests/namespace.yaml
  - todo-app/manifests/deployment.yaml
  - todo-app/manifests/ingress.yaml
  - todo-app/manifests/pvc.yaml
  - todo-app/manifests/service.yaml
  - todo-backend/manifests/deployment.yaml
  - todo-backend/manifests/hourly-todo.yaml
  - todo-backend/manifests/service.yaml
  - todo-backend/manifests/statefulset.yaml
secretGenerator:
  - name: todo-postgres-password
    literals:
      - POSTGRES_PASSWORD=${TODO_POSTGRES_PASSWORD}
