apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: project
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          volumes:
            - name: google-sa-key
              secret:
                secretName: google-sa-key
                items:
                  - key: GOOGLE_SERVICE_ACCOUNT_KEY
                    path: key.json
          containers:
            - name: postgres-backup
              image: google/cloud-sdk:553.0.0-slim
              env:
                - name: PGHOST
                  valueFrom:
                    configMapKeyRef:
                      name: postgres-config
                      key: POSTGRES_HOST
                - name: PGPORT
                  valueFrom:
                    configMapKeyRef:
                      name: postgres-config
                      key: POSTGRES_PORT
                - name: PGUSER
                  valueFrom:
                    configMapKeyRef:
                      name: postgres-config
                      key: POSTGRES_USER
                - name: PGDATABASE
                  valueFrom:
                    configMapKeyRef:
                      name: postgres-config
                      key: POSTGRES_DATABASE
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: todo-postgres-password
                      key: POSTGRES_PASSWORD
                - name: GOOGLE_APPLICATION_CREDENTIALS
                  value: /var/secrets/google/key.json
              volumeMounts:
                - name: google-sa-key
                  mountPath: /var/secrets/google
              command:
                - /bin/sh
                - -c
                - |
                  set -eu
                  TIMESTAMP=$(date +"%Y-%m-%d-%H-%M-%S")
                  apt-get update && apt-get install -y postgresql-client
                  pg_dump -v > /tmp/backup.sql
                  gcloud auth activate-service-account --key-file "$GOOGLE_APPLICATION_CREDENTIALS"
                  gsutil cp /tmp/backup.sql gs://vejolkko-todo-backup/backup_$TIMESTAMP.sql
