apiVersion: batch/v1
kind: CronJob
metadata:
  name: hourly-todo
  namespace: project
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: hourly-todo-cron
              image: curlimages/curl:8.18.0
              env:
                - name: BACKEND_URL
                  value: "http://todo-backend-svc:2345/todos"
                - name: WIKIPEDIA_RADMOM_URL
                  value: "https://en.wikipedia.org/wiki/Special:Random"
              command:
                - /bin/sh
                - -c
                - |
                  ARTICLE_URL=$(curl -L -o /dev/null -w %{url_effective} $WIKIPEDIA_RADMOM_URL)
                  curl -X POST $BACKEND_URL \
                    -H "Content-Type: application/json" \
                    -d "{\"content\": \"Read $ARTICLE_URL\"}"
