apiVersion: v1
kind: Secret
metadata:
    name: todo-postgres-secret
    namespace: project
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:5l3dSD7T1A8=,iv:us2dGkCykBwatsbnOzJWjcjwhVuWvaDqTHgCvV6JbPA=,tag:dsV3C592QohvXISs7BF+qw==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:G7pk5iY2YeU=,iv:Y5ptH1r2cChj1fRC3r9/tZjH28d2zbsfw5w983c1zo0=,tag:0m55FfY9QlB62Wg8vHUMyw==,type:str]
    POSTGRES_DATABASE: ENC[AES256_GCM,data:X+Dg9Nt6UWU=,iv:/LvI3kzSdyj8snnwXEHtAOQCTTT0Lrkga2tY57pMrnI=,tag:yAhoroPzrIxoq7DwJVsyWw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w6csmk7r86jcprkkkr6chw6m9q8vugd9zvy78zcpvfp8repq4fns36l9np
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1T2gxK2MxWnJjSjJIN1Rh
            THE3ZGpvR04za044YzhMWmsyNEw4K3NEeUVJCnNyV3N5RVpHYkFRVmVkRExCT2Ex
            MXpGMnc2L2VpMHBMOXByVjdNRUJsQ2sKLS0tIGRlOFhsZFBSSHpsQXVjL3ZTVGM4
            N0t6MVBmd3dRa013amt4TXFMblBsM0EKgkqSFTH79yGbFh5N7tb3Orzi2M5tsZDV
            j7/2X13CKKAre5uVZ11w/0+6Hw4bACZPrR5ofS1SraaAOqmammG3PA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-22T08:37:25Z"
    mac: ENC[AES256_GCM,data:GHlQAterDdC42cEgfK4mcvVZM/Xcg4P5ITRzEJ6LopgX3UV7V6CuqO2kkucX0HUSTQbCR5z0a80k2mnpaT9aBe8w8g/SwydV4d5mFFKH50fnNKbD35ywRAM0pV5w7GnET1G3oF7yE9PP6NaMJeFOGqqhbx42UraxXJmhSrSrsy8=,iv:WADf1C4F+/Jn3SMCTvdwyZDOhYEiEDquaOIZSi+0q2M=,tag:wI6r+gCDRxuy2P3mhPay0A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
