apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: project
stringData:
    FULLSTACK_DISCORD_WEBHOOK: ENC[AES256_GCM,data:lW5JYijlHnlj73OoutTwylmz88fH0bKOeRkNwuAX3gUqVSsPw6w8bI8IGJF0TS4KFn6LCUHbFasDJfYZae56QBQ=,iv:AdqBoUFRnvCiVGjDl5Mr0i6pNaWm2rq4nMaawwCbRPI=,tag:pXPP02jM8hcp1/VIUmen9Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w6csmk7r86jcprkkkr6chw6m9q8vugd9zvy78zcpvfp8repq4fns36l9np
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsUkU5RXQyRGkwYW9ROUxO
            MGpYemI5dzdIZmo1YmpZa2VKU1lpbVplTkZVCjZzUG9ZRy9rNzlVOWNvTi9YM29o
            bTF4YUVJRDYwcHdwTlpxNG00MVZodDAKLS0tIDgyaWN6ck9TZ1NGOHY3VSsyK1J4
            TzRDTlozSTVoRjZlM2t2QWhDWFZjZkUKDQGZY3+8yPWbdCfZoxEdQ/ZyLskEkKJT
            TgwnpX+pkl248J7ME6A0BUi+pBajJJbcM+dK14zPlgd8Vk/9xogoyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-31T18:22:26Z"
    mac: ENC[AES256_GCM,data:yqoOO+GSmhGj85S024/vvCKJbL8BHLCSKgaixZOmzskzJsjPxtFNVTgzVCWwLSiBCVUhV2hMSJxqasO3WkWTetsiQ66OY4DRoFxa1GBYua1Bz6spTfP0Y8smbdirbV3/o+uU6cpB0lC6At35Iw9VLKdJN0Pm5n107XfxrTASrZM=,iv:9wTrzLp27ITiElNX1hGXMOxvFXI07UW921tD2/B4tbc=,tag:x7ORyz6ZhKm5NDT1/9C7lQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
