apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-hash
          emptyDir: {}
      containers:
        - name: hash-generator
          image: vesajo/hash-generator@sha256:c72fae48ff8943f8f2cb1b173b42b37f6ae3e8672cfbcb268d943dd3c711ed4b
          env:
            - name: HASH_FILE_PATH
              value: "/app/files/hash.txt"
          volumeMounts:
            - name: shared-hash
              mountPath: /app/files
        - name: hash-outputter
          image: vesajo/hash-outputter@sha256:2ef816c46323f89e0f72442ead4e7a6e401eab9a138a0ca79a98f11079f6dd14
          env:
            - name: PORT
              value: "3000"
            - name: PING_PONG_URL
              value: "http://ping-pong-svc:2345"
            - name: HASH_FILE_PATH
              value: "/app/files/hash.txt"
          volumeMounts:
            - name: shared-hash
              mountPath: /app/files
