apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project-claim
  namespace: project
spec:
  storageClassName: project-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
