apiVersion: v1
kind: Secret
metadata:
    name: pingpong-postgres-secret
    namespace: exercises
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:qrXICYWJZBI=,iv:JQW+nIfFu4JaTn+emQlgpD+9Ai9tkukTobdaLBHYhDk=,tag:v1vgta5qBZxRLtsqhHgJBg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:6x2Sj4mixho=,iv:LD3V8q0OPd1/sxkLe6jGx7YL/gKZ4DKoSl/hiAuMBxI=,tag:AzyV3v9oUzn6+CpmjEsKZQ==,type:str]
    POSTGRES_DATABASE: ENC[AES256_GCM,data:eypTWgoOLO8=,iv:zf9sUI1Axa3rGNz6QpH+X8bdNKQ6SNr1geNGRzfqAFM=,tag:sz71fkuM9OuMudYItU1Lug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w6csmk7r86jcprkkkr6chw6m9q8vugd9zvy78zcpvfp8repq4fns36l9np
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwTWxQMTA2dlVmT2MrczEy
            S1NLaVQvakRyUUVGQ0pCV3JMT2NyLzcxUlFNClNYSE5MS1FmMnpZVFQwbjdYa2t4
            akhNUHVaNEZGVis3dVVGY2NvS0tURlEKLS0tIGU1TlYzTVBkKysvVk9DaFJ3ZUhj
            Tys5ckViTWR1YmRIeG9TZ3YwSnlHWEUKWo5VnidJ6lWoLLlsscRYuNHvxx7z3p2h
            9ZCOcsusSF+mdX4+GlJ/5Cou6QVeCrZMmQKa9cNGW3o2sHyzwMlzfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T19:23:58Z"
    mac: ENC[AES256_GCM,data:/Kvhw1glSyDQFFC3lVun2zc8UB2jl4vT15OWkhnFa3pLrMcbTpAFzP1dIJEQjzEf64qVsfy511uviGmzO4QJvozzh5DXu4wSBftjHtlUtEiJ+e+hUm8vuV2ZdueFfBOxQ7Hr+hATBO4Zsw+NVuAsr1kfRD0SA7FJ6cv9+YGkHsc=,iv:5NhWIiQb/4QkGsbrIKEi0LfXGUbllbXC9afA/pYKHUU=,tag:b3NV4po1fo5yLqCfhNQ8BA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
