apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pingpong-postgres-stset
  namespace: exercises
spec:
  serviceName: pingpong-postgres-svc
  replicas: 1
  selector:
    matchLabels:
      app: pingpong-postgres
  template:
    metadata:
      labels:
        app: pingpong-postgres
    spec:
      containers:
        - name: pingpong-postgres
          image: postgres:18
          envFrom:
            - secretRef:
                name: pingpong-postgres-secret
          ports:
            - name: web
              containerPort: 5432
          volumeMounts:
            - name: pingpong-postgres-storage
              mountPath: /var/lib/postgresql
  volumeClaimTemplates:
    - metadata:
        name: pingpong-postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Mi

---
apiVersion: v1
kind: Service
metadata:
  name: pingpong-postgres-svc
  namespace: exercises
  labels:
    app: pingpong-postgres
spec:
  ports:
    - port: 5432
      name: web
  clusterIP: None
  selector:
    app: pingpong-postgres
