apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-hash
          emptyDir: {}
        - name: info-file
          configMap:
            name: log-output-config
            items:
              - key: information.txt
                path: information.txt
      containers:
        - name: hash-generator
          image: vesajo/hash-generator@sha256:c864d479817f8705f6a8369bc7b2a6b1b69c0b5f0678477980db16fb5ad2b156
          env:
            - name: HASH_FILE_PATH
              value: "/app/files/hash.txt"
          volumeMounts:
            - name: shared-hash
              mountPath: /app/files
        - name: hash-outputter
          image: vesajo/hash-outputter@sha256:f7edb77bedab90f93de6d694d0ee093071401eb5b62270f8a0da005c6463ba91
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
              path: /readyz
              port: 3000
          env:
            - name: PORT
              value: "3000"
            - name: PING_PONG_URL
              value: "http://ping-pong-svc:80"
            - name: HASH_FILE_PATH
              value: "/app/files/hash-file/hash.txt"
            - name: INFO_FILE_PATH
              value: "/app/files/info-file/information.txt"
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-config
                  key: MESSAGE
          volumeMounts:
            - name: shared-hash
              mountPath: /app/files/hash-file
            - name: info-file
              mountPath: /app/files/info-file
