apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-hash
          emptyDir: {}
        - name: shared-count
          persistentVolumeClaim:
            claimName: log-output-claim
      containers:
        - name: hash-generator
          image: vesajo/hash-generator@sha256:56fb0028e7a4504d94ea1dc8488919715f476c9c8c92e5d3275228f3cb8fb2ad
          volumeMounts:
            - name: shared-hash
              mountPath: /app/hash
        - name: hash-outputter
          image: vesajo/hash-outputter@sha256:48d9028f02ee2f172130574f70bf8b048c4fbdb40768d426530b3bb0bf90c34d
          volumeMounts:
            - name: shared-hash
              mountPath: /app/hash
            - name: shared-count
              mountPath: /app/files
