apiVersion: v1
kind: ConfigMap
metadata:
  name: log-output-config
  namespace: exercises
data:
  MESSAGE: "hello from ConfigMap!"
  information.txt: |
    This message is from file managed by ConfigMap
