name: Remove Kubernetes namespace

on: delete

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT_ID }}
  GKE_CLUSTER: kubernetes-course
  GKE_ZONE: europe-north1-b
  BRANCH: ${{ github.ref_name }}

jobs:
  delete-namespace:
    name: Delete Kubernetes namespace
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest

    steps:
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GKE_SA_KEY }}"

      - name: "Set up Cloud SDK"
        uses: google-github-actions/setup-gcloud@v2

      - name: "Use gcloud CLI"
        run: gcloud info

      - name: "Get GKE credentials"
        uses: "google-github-actions/get-gke-credentials@v2"
        with:
          cluster_name: "${{ env.GKE_CLUSTER }}"
          project_id: "${{ env.PROJECT_ID }}"
          location: "${{ env.GKE_ZONE }}"

      - name: Delete Kubernetes namespace
        run: kubectl delete namespace ${{ github.event.ref }}
