name: Release application

on:
  push:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: kubernetes-course
  GKE_ZONE: europe-north1-b
  REGISTRY: europe-north1-docker.pkg.dev
  REPOSITORY: kubernetes-course
  BACKEND_IMAGE: todo-backend
  FRONTEND_IMAGE: todo-app
  DEPLOYMENT_NAME: todo-app-dep
  BRANCH: ${{ github.ref_name }}

jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GKE_SA_KEY }}"

      - name: "Set up Cloud SDK"
        uses: google-github-actions/setup-gcloud@v2

      - name: "Use gcloud CLI"
        run: gcloud info

      - run: gcloud --quiet auth configure-docker $REGISTRY

      - name: "Get GKE credentials"
        uses: "google-github-actions/get-gke-credentials@v2"
        with:
          cluster_name: "${{ env.GKE_CLUSTER }}"
          project_id: "${{ env.PROJECT_ID }}"
          location: "${{ env.GKE_ZONE }}"

      - name: "Form the backend image name"
        run: echo "BACKEND_IMAGE_NAME=$REGISTRY/$PROJECT_ID/$REPOSITORY/$BACKEND_IMAGE:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV

      - name: Build todo-backend
        run: docker build --tag "$BACKEND_IMAGE_NAME" ./chapter4/project/todo-backend

      - name: Publish todo-backend
        run: docker push $BACKEND_IMAGE_NAME

      - name: "Form the frontend image name"
        run: echo "FRONTEND_IMAGE_NAME=$REGISTRY/$PROJECT_ID/$REPOSITORY/$FRONTEND_IMAGE:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV

      - name: Build todo-app
        run: docker build --tag "$FRONTEND_IMAGE_NAME" ./chapter4/project/todo-app

      - name: Publish todo-app
        run: docker push $FRONTEND_IMAGE_NAME

      - name: Set TODO_POSTGRES_PASSWORD to environment variable from secrets
        run: echo "TODO_POSTGRES_PASSWORD=${{ secrets.TODO_POSTGRES_PASSWORD }}" >> $GITHUB_ENV
      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2.1.0

      - name: Deploy
        working-directory: ./chapter4/project
        run: |-
          kustomize edit set image TODO_BACKEND=$BACKEND_IMAGE_NAME
          kustomize edit set image TODO_APP=$FRONTEND_IMAGE_NAME
          kustomize build . | kubectl apply -f -
          kubectl config set-context --current --namespace=project
          kubectl rollout status deployment $DEPLOYMENT_NAME
          kubectl get services -o wide
