apiVersion: v1
kind: Secret
metadata:
    name: todo-postgres-password
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:d2e/TvVLO3U=,iv:Uk1lLEOB02uFNhg/L2kZ2ZiJhNxycs4pLIhHr2ZdS20=,tag:qaoskkNSQpXEEqfzzWYeJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w6csmk7r86jcprkkkr6chw6m9q8vugd9zvy78zcpvfp8repq4fns36l9np
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtYVE0SGpYbFB6eU5nQ1Jj
            ZC9HMWtXRTZtRjB6OGx5MXV3c1d3RW5NSWdNCjdzMU5nSmhQMUdGS25tWVFyMXly
            N2ovcDlmMW5GV3ljcTlnTzYyTzRnUHMKLS0tIHpMUFdTbVpLa0ZJZStQUnhjeHFm
            SXNWS1d6bVhUaHRGcGtwaHNhUnpoUmMKx2eJwF/qVE+YGyLXmUWN2tb/juz62zSL
            Q4oNBZ5A+6nIPo6DeGlYxWMW+EkehD7WUc8o+s2r0m/ghALdSXmZIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T13:06:33Z"
    mac: ENC[AES256_GCM,data:9Utk0QJyC+jovd9+FAHgxABgTnHlz4YRD96vjVKKasRWsQ8hvEwk5UAEd+fCA18rdFcuKZqYKfC40iT9Vh7KtXgzw+SaxwzaC9cq14hZ3+yXU3tZSZP6/AB3gCSVVeEU07U+ReyoTFZdPekht0fb8OdtRO28qSfG0Un4dCrKOQM=,iv:V/5Tt+AYTuo8DTfWu7hqls0Lv01qM2m8nuSKbflTSPQ=,tag:1+yKwtlOOUcVqODyC4K1IQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
