apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: todo-postgres-stset
  namespace: project
spec:
  serviceName: todo-postgres-svc
  replicas: 1
  selector:
    matchLabels:
      app: todo-postgres
  template:
    metadata:
      labels:
        app: todo-postgres
    spec:
      containers:
        - name: todo-postgres
          image: postgres:15
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          envFrom:
            - secretRef:
                name: todo-postgres-password
          ports:
            - name: web
              containerPort: 5432
          volumeMounts:
            - name: todo-postgres-storage
              mountPath: /var/lib/postgresql/data
          resources:
            limits:
              cpu: "100m"
              memory: "100Mi"
            requests:
              cpu: "10m"
              memory: "50Mi"

  volumeClaimTemplates:
    - metadata:
        name: todo-postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Mi

---
apiVersion: v1
kind: Service
metadata:
  name: todo-postgres-svc
  namespace: project
  labels:
    app: todo-postgres
spec:
  ports:
    - port: 5432
      name: web
  clusterIP: None
  selector:
    app: todo-postgres
